### ISSUE TITLE
SSL enabled wiki throws mixed content errors

### ISSUE THREAD

**Issue by heymatthew** [fedwiki/wiki-security-passportjs#4]
As an author who would like to participate and link to other Federated Wikis
I would like to take my SSL Wiki, and make links to articles on wikis without HTTPS
So that I can participate in a community

I've configured an instance of Federated Wiki based on the [Passport instructions](https://github.com/fedwiki/wiki-security-passportjs) behind Caddy on [wiki.matthew.nz](https://wiki.matthew.nz).

Running this SSL enabled Wiki throws up mixed content errors and displays "We could not find this page" when trying to link to non SSL wiki sites such as http://sites.fed.wiki.org

This URL demonstrates the issue:
https://wiki.matthew.nz/view/welcome-visitors/view/federated-wiki/view/sitesfedwikiorg

I've gone over the instructions a few times but am not sure what I can do next.

Am I doing something wrong?

**Comment by wohyah** [comment]
I'm running the wiki using the command
> wiki --data /wiki -p 3000 --config /wiki/config.json --url wiki.matthew.nz

My `config.json` has these settings
```
{
  "farm": false,
  "url": "wiki.matthew.nz",
  "security_useHttps": true,
  "security_type": "passportjs",
  "github_clientID": "SUPERSECRET",
  "github_clientSecret": "SUPERSUPERSECRETSECRET"
}
```

**Comment by paul90** [comment]
`security_useHttps` is only used so that the OAuth login is completed over a https connection. This has been added in part because many OAuth providers suggest that the login is completed over https, and some require it. But, also on a first step to getting into a position where using the wiki over TLS.

Currently, there are elements in the client that have `http` hard-wired, this will be part of why you are seeing mixed content errors. Also very few servers in the federation currently support TLS, so even if the client was protocol neutral only a limited portion of the federation would currently be accessible over TLS.

**Comment by wohyah** [comment]
I'm a little unsettled by doing auth over plaintext these days.
Given that SSL is now effectively free, is this something that is already on the radar?

If this isn't being worked on, but is a desired thing, I might be able to hack together some proof of concept.

**Comment by paul90** [comment]
How the auth is done is governed by the OAuth identity provider, and will always be over TLS. All the parameter does is determine if the sub-window that the user selects which OAuth provider to use, and the final callback, is to use TLS. Some OAuth providers, such as Salesforce.com, insist that the final callback uses TLS, while some only recommend it or are quiet on the matter.

Personally I would like to see all servers providing their content over both http and https, but that is not where we currently are.

We have making the client protocol agnostic high on the list, though the current priority is getting past the Mozilla Persona close at the end of this month. 

While making the client protocol agnostic should remove the mixed content errors, it will make any sites in the federation that are still to support TLS invisible to those connecting to their origin server using https.

**Comment by WardCunningham** [comment]
@wohyah, For higher security you might consider running your public server with the default security module and then pushing content over ssh from a private clone. I run one site this way because a client insisted it be an alternative. I run this command whenever I finish editing.
```
rsync -avz ~/.wiki/code.localhost/pages fed.wiki.org:farm/code.fed.wiki.org/
```

**Comment by paul90** [comment]
If you use the rsync option, you will need to also remove the sitemap files from the site's status directory. The site in the example above is using the old ruby server that creates that file on each request, rather than when the page data changes.

**Comment by wohyah** [comment]
After seeing failed requests to `http://localhost:8080/ipfs/...` I started down the rabbit hole of learning about IPFS. Given that has signing and secure transmission, I think that might actually cover my requirements for a public read only and private read write style wiki.

All that aside, I'm still interested in keeping auth cookies secret, setting up a wiki server with ACME and hook it up to the Lets Encrypt servers. That would let the wiki be served over HTTP and HTTPS thing that @paul90 suggests and include everyone.

Where's the best place to start hacking?

**Comment by paul90** [comment]
While IPFS is an interesting technology, currently there are only a handful of items that are using it, and they are mostly hand coded. There is an idea to use IPFS as a media commons for the federation, as well as a possible long term store for published content.

By the 'auth cookie', do you mean the wikiSession cookie? If so you will want to start with [fedwiki/wiki-server](https://github.com/fedwiki/wiki-server) and make the cookie *secure*.

The client code is over in [fedwiki/wiki-client](https://github.com/fedwiki/wiki-client). I'm not sure which of the plug-ins are also affected.

**Comment by WardCunningham** [comment]
@paul90, Good catch. Note to self: when you upgrade, add this to your release procedure.
```
ssh fed.wiki.org 'rm .wiki/code.fed.wiki.org/status/sitemap.*'
```

**Comment by paul90** [comment]
@wohyah As we had some changes for cookie duration for an alternative security plugin. I've added a parameter to set the `secure` flag on the session cookie. *We actually set `secureProxy` as we are using node-client-sessions, and the secure link is terminated outside the node process*

If you have the time to start looking at the wiki-client, that will be great.

**Comment by WardCunningham** [comment]
Developer guide to (part of) our codebase.
http://dev.asia.wiki.org/

**Comment by paul90** [comment]
There is now an updated version of the client, and those plugins that needed updating, that will get content using the same protocol as origin.

I was in two minds about how to handle the site flags. Currently there are still using `http`, this gives us an easy way of seeing if the remote site is running or not (the flag will be present if it is), as well as seeing if it supports `https`. If it doesn't the sitemap load fails to load, and the flag will be canted over at 15° in the neighbourhood bar.

So, it will be important to set `secure_cookie` to stop the cookie being sent over http to the origin site.

**Comment by paul90** [comment]
Something to note is that we will be unable to load pages from sites that don't have https support.

Building on your example above, https://rodwell.me/view/welcome-visitors/wiki.matthew.nz/federated-wiki , will get a page from both our sites as they both have https support. You will notice that the `sites.fed.wiki.org` icon in the neighbourhood is canted over at 15°, indicating that while the site is running we have failed to load its sitemap as it does not had https support.

This happens because json files are considered to be active content, and so the browser will refuse to load it over http. The images do load over http as they are considered passive/display content, but cause the mixed content warnings.

This has the effect that the neighbourhood is reduced to only include those sites which have https support. It now becomes a matter of peer pressure to get others to upgrade their sites to have support.

**Comment by WardCunningham** [comment]
There will surely be historical content that will never convert.

Rather than narrowing our federation we could turn to those sites supporting ssl to serve as gateway proxies. We have proxied content through the origin server before and discovered it is a bad idea, mostly because one ends up crossing firewalls the wrong way. We could restore the practice as a fallback.

There are variations of fork that still do remoteGet() so there is some precedent. The fork button itself doesn't use this because I fork pages across firewalls all of the time. I'm happy to dig into these cases further if ssl conversion propagates down here. It must, no?

https://github.com/fedwiki/wiki-server/blob/master/lib/server.coffee#L138-L166

(p.s. again many thanks to @paul90 for tackling these tough jobs)

**Comment by paul90** [comment]
@matthewbgray - the current version of wiki, 0.11.3, provides a solution to the points discussed at the start of this issue. This version of wiki changes how we connect with sites, adding a step that determines how that connection is made. This includes handling remote sites that are https only, as well as the need to proxy if we are using https and the remote is not (this is only provided for an authenticated site owner).

If you set both `security_useHttps` and `secure_cookie` to true, the site will be editable only over https.
